---
title: "Pleural protein dilution series"
subtitle: "Results from Olink Target 96 Inflammation panel"
date: "`r format(Sys.time(), '%d %B %Y')`"
author: Paul Yousefi
output:
  html_document:
    css: docs/style.css
    toc: true
    highlight: tango
---

```{r setoptions, eval = TRUE, echo = FALSE}
knitr::opts_chunk$set(
comment = ">",
error = FALSE,
tidy = FALSE,
echo = F, 
warning = FALSE, 
message = FALSE,
cache=FALSE)
```

```{r call_source, echo = F}
path <- "."
sourcecode <- grep("dilution-series-qc.r$", 
	list.files(path), value = T)
read_chunk(file.path(path, sourcecode))
```

# Background 

16 samples from previous pleural fluid olink inflammation analysis (""GB390725-RB_pleural fluid_NPX.csv") was re-run at several different concentration dilutions in order to find the optimal conditions for further analysis.

## Design

Counts by dilution fraction below:

```{r globals, results = 'hide', echo=F }
```

```{r load.data}
```

```{r access.pheno}
```
```{r dilutions}
```

`patient.ids` in each dilution:

```{r dilution.ids, echo = T}
```

